# Generated by Django 4.1.6 on 2023-02-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_categoria_options_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['id'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
