# Generated by Django 4.1.6 on 2023-02-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_productos_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
    ]
