# Generated by Django 4.1.6 on 2023-02-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_producto_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Beneficiario',
        ),
        migrations.AlterModelOptions(
            name='beneficiario',
            options={'ordering': ['id'], 'verbose_name': 'Beneficiario', 'verbose_name_plural': 'Beneficiario'},
        ),
        migrations.RenameField(
            model_name='suministro',
            old_name='cliente',
            new_name='beneficiario',
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/%Y/%m/%d'),
        ),
    ]
