# Generated by Django 4.1.6 on 2023-02-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_cliente_beneficiario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='pvp',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
