# Generated by Django 4.1.6 on 2023-02-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_beneficiario_sexo_beneficiario_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='genero',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='sexo',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo'),
        ),
    ]
