# Generated by Django 4.1.6 on 2023-02-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_beneficiario_genero_beneficiario_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesuministro',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='detallesuministro',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='suministro',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='suministro',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='sexo',
            field=models.CharField(choices=[('Male', 'Masculino'), ('Female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo'),
        ),
    ]
