# Generated by Django 4.1.6 on 2023-02-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_detallesuministro_precio_detallesuministro_subtotal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallesuministro',
            old_name='producto',
            new_name='productos',
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/%Y/%m/%d', verbose_name='Imagen'),
        ),
    ]
