# Generated by Django 4.1.6 on 2023-02-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_producto_detallesuministro_productos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallesuministro',
            old_name='productos',
            new_name='producto',
        ),
    ]
