# Generated by Django 4.1.7 on 2023-03-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='estado',
        ),
    ]
