# Generated by Django 4.1.7 on 2023-03-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_autor_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='descripcion',
            new_name='descripciones',
        ),
    ]
