# Generated by Django 4.1.6 on 2023-03-04 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_descripcion_autor_descripciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiario',
            old_name='sexo',
            new_name='gender',
        ),
    ]
