# Generated by Django 4.1.7 on 2023-03-04 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_sexo_beneficiario_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='gender',
            field=models.CharField(choices=[('Male', 'Masculino'), ('Female', 'Femenino')], default='male', max_length=10, verbose_name='Genero'),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('f_publicacion', models.DateField(max_length=50)),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.autor')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
    ]
