# Generated by Django 4.1.7 on 2023-03-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_beneficiario_gender_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='descripciones',
            new_name='descripcion',
        ),
    ]
