# Generated by Django 4.1.7 on 2023-03-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_rename_descripciones_autor_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='cedula',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='barrio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='documento',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='tipoDocumento',
            field=models.CharField(choices=[('Registro Civil', 'Registro Civil'), ('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Cédula de Extrajería', 'Cédula de Extrajería'), ('Contraseña Registraduría', 'Contraseña Registraduria')], default='Registro Civil', max_length=25, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='zona',
            field=models.CharField(choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], default='Urbana', max_length=25, verbose_name='Zona'),
        ),
    ]
