# Generated by Django 4.1.7 on 2023-03-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_beneficiario_cedula_beneficiario_barrio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='gender',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='Femenino', max_length=25, verbose_name='Genero'),
        ),
    ]
