# Generated by Django 4.1.6 on 2023-03-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_beneficiario_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['id'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
