# Generated by Django 4.1.6 on 2023-03-11 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_autor_options_alter_libro_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='fecha_creacion',
        ),
    ]
