# Generated by Django 4.1.6 on 2023-03-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_libro_cantidad_libro_descripcion_libro_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='apellidos',
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombres',
            field=models.CharField(max_length=45, verbose_name='Nombres y Apellidos'),
        ),
    ]
