# Generated by Django 4.1.7 on 2023-03-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_libro_genero_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='fecha_creacion',
        ),
    ]
