# Generated by Django 4.1.7 on 2023-03-16 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_remove_autor_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
