# Generated by Django 4.1.7 on 2023-03-17 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_libro_f_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to='Eventos/', verbose_name='Imagen')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha y Hora')),
                ('tipoEvento', models.CharField(max_length=50)),
            ],
        ),
    ]
