# Generated by Django 4.1.7 on 2023-03-19 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_eventos_alter_autor_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cantidad_dias',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='user',
        ),
        migrations.AddField(
            model_name='reserva',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.beneficiario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.libro'),
        ),
    ]
