# Generated by Django 4.1.7 on 2023-03-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
