# Generated by Django 4.1.7 on 2023-03-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_reserva_options_remove_reserva_cantidad_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Ubicación'),
        ),
    ]
