# Generated by Django 4.1.7 on 2023-03-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_reserva_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Cantidad o Stock'),
        ),
    ]
