# Generated by Django 4.1.7 on 2023-03-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_productos_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='stock',
        ),
    ]
