# Generated by Django 4.1.7 on 2023-03-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_remove_productos_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad o Stock'),
        ),
    ]
