# Generated by Django 4.1.7 on 2023-03-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_productos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Cantidad o Stock'),
        ),
    ]
