# Generated by Django 4.1.7 on 2023-03-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_productos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad o Stock'),
        ),
    ]
