# Generated by Django 4.1.7 on 2023-03-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_productos_tipobeneficio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='tipoBeneficio',
        ),
        migrations.AddField(
            model_name='productos',
            name='tipo',
            field=models.CharField(choices=[('Donación', 'Donación'), ('Prestamo', 'Prestamo')], default='Donación', max_length=25, verbose_name='Tipo de Producto'),
        ),
    ]
