# Generated by Django 4.1.7 on 2023-03-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_beneficiario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='tipo',
            field=models.CharField(choices=[('Funcionario', 'Funcionario'), ('Lector', 'Lector')], default='Funcionario', max_length=25, verbose_name='Tipo'),
        ),
    ]
