# Generated by Django 4.1.7 on 2023-03-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_alter_beneficiario_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha',
            new_name='fecha9',
        ),
    ]
