# Generated by Django 4.1.7 on 2023-03-20 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_rename_fecha_reserva_fecha9'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha8',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
    ]
