# Generated by Django 4.1.7 on 2023-03-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_reserva_fecha8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='tipo',
            field=models.CharField(choices=[('Funcionario', 'Funcionario'), ('Beneficiario', 'Beneficiario')], default='Funcionario', max_length=25, verbose_name='Tipo'),
        ),
    ]
