# Generated by Django 4.1.7 on 2023-03-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_alter_beneficiario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
