# Generated by Django 4.1.7 on 2023-03-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_autor_estado_eventos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
