# Generated by Django 4.1.7 on 2023-03-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_eventos_ubicacion_alter_eventos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
    ]
