# Generated by Django 4.1.7 on 2023-04-07 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_eventos_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('tipoDocumento', models.CharField(choices=[('Registro Civil', 'Registro Civil'), ('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Cédula de Extrajería', 'Cédula de Extrajería'), ('Contraseña Registraduría', 'Contraseña Registraduria')], default='Registro Civil', max_length=25, verbose_name='Tipo de Documento')),
                ('documento', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Documento')),
                ('cumpleaños', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('tipo', models.CharField(choices=[('Funcionario', 'Funcionario'), ('Beneficiario', 'Beneficiario')], default='Funcionario', max_length=25, verbose_name='Tipo')),
                ('zona', models.CharField(choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], default='Urbana', max_length=25, verbose_name='Zona')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion')),
                ('barrio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Barrio')),
                ('gender', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='Femenino', max_length=25, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Lector',
                'verbose_name_plural': 'Lectores',
                'ordering': ['id'],
            },
        ),
    ]
