# Generated by Django 4.1.7 on 2023-04-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_lector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='tipo',
        ),
    ]
