# Generated by Django 4.1.7 on 2023-04-08 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_remove_lector_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='beneficiario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='lector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.lector'),
        ),
    ]
