# Generated by Django 4.1.7 on 2023-04-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_alter_reserva_estados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='tipo',
            field=models.CharField(choices=[('Beneficiario', 'Beneficiario')], default='Beneficiario', max_length=25, verbose_name='Tipo'),
        ),
    ]
