# Generated by Django 4.1.7 on 2023-04-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_reserva_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='estados',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default=('Entregado', 'Entregado'), max_length=25, verbose_name='Estado'),
        ),
    ]
