# Generated by Django 4.1.7 on 2023-04-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_remove_reserva_estados_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
