# Generated by Django 4.1.7 on 2023-04-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
