# Generated by Django 4.1.7 on 2023-04-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_productos_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='tipo',
        ),
    ]
