# Generated by Django 4.2 on 2023-04-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_remove_productos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo(Si) Inactivo(No)'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Donación(si) Préstamo(No)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.BooleanField(default=True, verbose_name=' Entregada(Si) Recibido(No)'),
        ),
    ]
