# Generated by Django 4.2 on 2023-04-27 12:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_reserva_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Visible(Si) Oculto(No)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.BooleanField(default=True, verbose_name=' Entregada(Si) Devolución(No)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha8',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha Devolución'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha9',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha Entrega'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.libro'),
        ),
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/%Y/%m/%d', verbose_name='Imagen')),
                ('stock', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Cantidad o Stock')),
                ('pvp', models.DecimalField(blank=True, decimal_places=0, default=0.0, max_digits=9, null=True, verbose_name='Precio')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['id'],
            },
        ),
    ]
