# Generated by Django 4.2 on 2023-04-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_alter_eventos_estado_alter_reserva_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria Libro',
                'verbose_name_plural': 'Categorias Libros',
                'ordering': ['id'],
            },
        ),
    ]
