# Generated by Django 4.2 on 2023-04-27 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_categorialibro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='categoriaLibro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.categorialibro'),
        ),
    ]
