# Generated by Django 4.2 on 2023-04-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_libro_categorialibro'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(max_length=3, null=True, unique=True, verbose_name='Codigo'),
        ),
    ]
