# Generated by Django 4.2 on 2023-04-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_categoria_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='codigo',
        ),
        migrations.AddField(
            model_name='categorialibro',
            name='codigo',
            field=models.CharField(max_length=3, null=True, unique=True, verbose_name='Codigo'),
        ),
    ]
