# Generated by Django 4.2 on 2023-05-08 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_alter_categorialibro_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='categorialibro',
            name='codigo',
            field=models.CharField(max_length=3, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='categoriaLibro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.categorialibro', verbose_name='Categoría del Libro'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Visible(Sí) No Visible(No)'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
