# Generated by Django 4.2 on 2023-05-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_remove_reserva_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('Recibido', 'Recibido')], default='Entregado', max_length=25, verbose_name='Estado'),
        ),
    ]
