# Generated by Django 4.2 on 2023-05-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_alter_reserva_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='lector',
        ),
    ]
