# Generated by Django 4.2 on 2023-05-09 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_remove_reserva_lector'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='lector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.lector'),
        ),
    ]
