# Generated by Django 4.2 on 2023-05-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_reserva_lector'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
