# Generated by Django 4.2 on 2023-05-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_reserva_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='state',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
