# Generated by Django 4.2 on 2023-05-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0090_remove_reserva_state_alter_reserva_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='user',
        ),
    ]
