# Generated by Django 4.2 on 2023-05-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0091_remove_reserva_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.libro'),
        ),
    ]
