# Generated by Django 4.2 on 2023-05-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_alter_libro_titulo_alter_productos_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministro',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='suministro',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=9),
        ),
    ]
