# Generated by Django 4.2 on 2023-05-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0095_alter_detallesuministro_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Completo(Sí) Incompleto(No)'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Cantidad'),
        ),
    ]
