# Generated by Django 4.1.6 on 2023-03-05 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='imagen',
            new_name='image',
        ),
    ]
