# Generated by Django 4.1.6 on 2023-03-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_imagen_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='documento',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='user',
            name='tipoDocumento',
            field=models.CharField(choices=[('Registro Civil', 'Registro Civil'), ('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Cédula de Extrajería', 'Cédula de Extrajería'), ('Contraseña Registraduría', 'Contraseña Registraduria')], default='Registro Civil', max_length=25, verbose_name='Tipo de Documento'),
        ),
    ]
